//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetSuiviePatient.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicament
    {
        public int ID { get; set; }
        public string NomMedicament { get; set; }
        public string Description { get; set; }
        public string Posologie { get; set; }
        public string FormeMedicament { get; set; }
        public string Fabricant { get; set; }
    }
}
