//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetSuiviePatient.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendezvou
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateHeure { get; set; }
        public Nullable<int> MedecinID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string Motif { get; set; }
        public string Statut { get; set; }
        public string Remarques { get; set; }
        public string Urgence { get; set; }
    
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
